// Utility exports for prediction market integration
export {
    basisPointsToDecimal,
    decimalToBasisPoints,
    calculateProbabilitiesFromOrders,
    calculateProbabilitiesFromLiquidity,
    calculatePotentialReturn,
    calculateImpliedProbability,
    calculatePriceFromProbability,
    calculateTimeRemaining,
    getMarketStatus,
    isMarketActive,
    calculateAveragePrice,
    calculatePositionPnL,
    calculateSlippage,
    formatPrice,
    formatAmount,
    formatTimestamp,
    validateMarketQuestion,
    validateOrderAmount,
    calculateBreakEvenPrice,
    generateMarketId,
    sortMarkets,
    filterMarketsByStatus,
    calculatePositionSize,
    calculateConcentrationRisk
} from './prediction-market';